# Generated by Django 3.2.3 on 2021-10-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('pwd', models.IntegerField(blank=True, null=True)),
                ('writer', models.CharField(blank=True, max_length=20, null=True)),
                ('notice', models.IntegerField(blank=True, null=True)),
                ('hit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ars_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
            ],
            options={
                'db_table': 'bus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sigungu', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('post', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'care',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('land_name', models.CharField(blank=True, max_length=30, null=True)),
                ('square_m', models.IntegerField(blank=True, null=True)),
                ('wait_people', models.FloatField(blank=True, null=True)),
                ('supply_type', models.CharField(blank=True, max_length=16, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('fire_d', models.FloatField(blank=True, null=True)),
                ('station_d', models.FloatField(blank=True, null=True)),
                ('elementary_d', models.FloatField(blank=True, null=True)),
                ('post_d', models.FloatField(blank=True, null=True)),
                ('subway_d', models.FloatField(blank=True, null=True)),
                ('department_d', models.FloatField(blank=True, null=True)),
                ('police_d', models.FloatField(blank=True, null=True)),
                ('traditional_d', models.FloatField(blank=True, null=True)),
                ('convenience_d', models.FloatField(blank=True, null=True)),
                ('high_d', models.FloatField(blank=True, null=True)),
                ('kinder_d', models.FloatField(blank=True, null=True)),
                ('middle_d', models.FloatField(blank=True, null=True)),
                ('care_d', models.FloatField(blank=True, null=True)),
                ('bus_d', models.FloatField(blank=True, null=True)),
                ('hospital_d', models.FloatField(blank=True, null=True)),
                ('cluster', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cluster_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Convenience',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('large_category', models.CharField(blank=True, max_length=6, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=12, null=True)),
                ('small_category', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'convenience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField(blank=True, null=True)),
                ('large_category', models.CharField(blank=True, max_length=4, null=True)),
                ('medium_category', models.CharField(blank=True, max_length=10, null=True)),
                ('small_category', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'depart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('type_code', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('si_code', models.IntegerField(blank=True, null=True)),
                ('si', models.CharField(blank=True, max_length=4, null=True)),
                ('gu_code', models.IntegerField(blank=True, null=True)),
                ('gu', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('openday', models.DateField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kinder',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('edu_name', models.CharField(blank=True, max_length=24, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=14, null=True)),
                ('establish_date', models.DateField(blank=True, null=True)),
                ('openday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kinder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('station_code', models.IntegerField(blank=True, null=True)),
                ('large_category', models.CharField(blank=True, max_length=10, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=20, null=True)),
                ('small_category', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('sigungu', models.CharField(blank=True, max_length=10, null=True)),
                ('postal', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('openday', models.DateField(blank=True, null=True)),
                ('longitude', models.TextField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pharmacy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Police',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('agency', models.CharField(blank=True, max_length=20, null=True)),
                ('station', models.CharField(blank=True, max_length=20, null=True)),
                ('police_station', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'police',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('station_code', models.IntegerField(blank=True, null=True)),
                ('large_category', models.CharField(blank=True, max_length=10, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=20, null=True)),
                ('small_category', models.CharField(blank=True, max_length=22, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('school_id', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('classification', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'school',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seoul',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entrepreneur', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('address_gu', models.CharField(blank=True, max_length=20, null=True)),
                ('land_name', models.CharField(blank=True, max_length=40, null=True)),
                ('household', models.SmallIntegerField(blank=True, null=True)),
                ('housing_type', models.CharField(blank=True, max_length=10, null=True)),
                ('supply_type', models.CharField(blank=True, max_length=16, null=True)),
                ('wait_people', models.TextField(blank=True, null=True)),
                ('square_m', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seoul',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_id', models.IntegerField(blank=True, null=True)),
                ('large_category', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_category', models.CharField(blank=True, max_length=30, null=True)),
                ('small_category', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('station_num', models.SmallIntegerField(blank=True, null=True)),
                ('line_num', models.IntegerField(blank=True, null=True)),
                ('station_nam', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subway',
                'managed': False,
            },
        ),
    ]
