# Generated by Django 3.2.3 on 2021-10-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'notice_blog',
                'managed': False,
            },
        ),
    ]
