# Generated by Django 3.2.7 on 2021-10-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_noticeblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'commet',
                'managed': False,
            },
        ),
    ]
